"use client";

// GENERADO por scripts/generar-plantillas-dinamicas.js -- no editar a mano.
// Para agregar una plantilla, creá el archivo en esta carpeta y volvé a
// correr el script. El porqué de este archivo está en ese script.

import dynamic from "next/dynamic";
import type { ComponentType } from "react";

/** Lo que las páginas le pasan a cualquier plantilla. */
export interface PropsDePlantilla {
  invitation: Record<string, unknown>;
  guest?: unknown;
  isPersonalized?: boolean;
}

type Plantilla = ComponentType<PropsDePlantilla>;

// Cada plantilla tipa sus props un poco distinto (el `guest` sobre todo);
// acá se las trata a todas igual, que es como las páginas las usaban.
function cargar(importar: () => Promise<unknown>, nombre: string): Plantilla {
  return dynamic(() =>
    importar().then((m) => (m as Record<string, unknown>)[nombre] as Plantilla)
  );
}

// Cada entrada es su propio chunk: sólo se baja la que se renderiza. Va en un
// componente de CLIENTE a propósito -- next/dynamic desde un Server
// Component no parte el bundle (ver docs de Next, "Lazy Loading").
const PLANTILLAS: Record<string, Plantilla> = {
  AcrylicPopTemplate: cargar(() => import("./AcrylicPopTemplate"), "AcrylicPopTemplate"),
  AcrylicPopTemplateBubblegum: cargar(() => import("./AcrylicPopTemplateBubblegum"), "AcrylicPopTemplateBubblegum"),
  AcrylicPopTemplateScarlet: cargar(() => import("./AcrylicPopTemplateScarlet"), "AcrylicPopTemplateScarlet"),
  AcrylicPopTemplateSunset: cargar(() => import("./AcrylicPopTemplateSunset"), "AcrylicPopTemplateSunset"),
  AcrylicPopTemplateUltraViolet: cargar(() => import("./AcrylicPopTemplateUltraViolet"), "AcrylicPopTemplateUltraViolet"),
  AniversarioTemplate: cargar(() => import("./AniversarioTemplate"), "AniversarioTemplate"),
  AniversarioTemplateAzul: cargar(() => import("./AniversarioTemplateAzul"), "AniversarioTemplateAzul"),
  AniversarioTemplateBorgona: cargar(() => import("./AniversarioTemplateBorgona"), "AniversarioTemplateBorgona"),
  AniversarioTemplateDorado: cargar(() => import("./AniversarioTemplateDorado"), "AniversarioTemplateDorado"),
  AniversarioTemplateEsmeralda: cargar(() => import("./AniversarioTemplateEsmeralda"), "AniversarioTemplateEsmeralda"),
  AtelierDePapelTemplate: cargar(() => import("./AtelierDePapelTemplate"), "AtelierDePapelTemplate"),
  AtelierDePapelTemplateAzulTinta: cargar(() => import("./AtelierDePapelTemplateAzulTinta"), "AtelierDePapelTemplateAzulTinta"),
  AtelierDePapelTemplateBorgonaVino: cargar(() => import("./AtelierDePapelTemplateBorgonaVino"), "AtelierDePapelTemplateBorgonaVino"),
  AtelierDePapelTemplateGrisGrafito: cargar(() => import("./AtelierDePapelTemplateGrisGrafito"), "AtelierDePapelTemplateGrisGrafito"),
  AtelierDePapelTemplateVerdeSalvia: cargar(() => import("./AtelierDePapelTemplateVerdeSalvia"), "AtelierDePapelTemplateVerdeSalvia"),
  BabyShowerTemplate: cargar(() => import("./BabyShowerTemplate"), "BabyShowerTemplate"),
  BabyShowerTemplateCeleste: cargar(() => import("./BabyShowerTemplateCeleste"), "BabyShowerTemplateCeleste"),
  BabyShowerTemplateDorado: cargar(() => import("./BabyShowerTemplateDorado"), "BabyShowerTemplateDorado"),
  BabyShowerTemplateDurazno: cargar(() => import("./BabyShowerTemplateDurazno"), "BabyShowerTemplateDurazno"),
  BabyShowerTemplateMenta: cargar(() => import("./BabyShowerTemplateMenta"), "BabyShowerTemplateMenta"),
  BautismoTemplate: cargar(() => import("./BautismoTemplate"), "BautismoTemplate"),
  BautismoTemplateCeleste: cargar(() => import("./BautismoTemplateCeleste"), "BautismoTemplateCeleste"),
  BautismoTemplateMarfil: cargar(() => import("./BautismoTemplateMarfil"), "BautismoTemplateMarfil"),
  BautismoTemplateRosa: cargar(() => import("./BautismoTemplateRosa"), "BautismoTemplateRosa"),
  BautismoTemplateVerdeSalvia: cargar(() => import("./BautismoTemplateVerdeSalvia"), "BautismoTemplateVerdeSalvia"),
  BlackAndWhiteTemplate: cargar(() => import("./BlackAndWhiteTemplate"), "BlackAndWhiteTemplate"),
  BlackAndWhiteTemplateNegativo: cargar(() => import("./BlackAndWhiteTemplateNegativo"), "BlackAndWhiteTemplateNegativo"),
  BolaDeDiscotecaTemplate: cargar(() => import("./BolaDeDiscotecaTemplate"), "BolaDeDiscotecaTemplate"),
  BolaDeDiscotecaTemplateEsmeralda: cargar(() => import("./BolaDeDiscotecaTemplateEsmeralda"), "BolaDeDiscotecaTemplateEsmeralda"),
  BolaDeDiscotecaTemplateFucsiaElectrico: cargar(() => import("./BolaDeDiscotecaTemplateFucsiaElectrico"), "BolaDeDiscotecaTemplateFucsiaElectrico"),
  BolaDeDiscotecaTemplateTurquesa: cargar(() => import("./BolaDeDiscotecaTemplateTurquesa"), "BolaDeDiscotecaTemplateTurquesa"),
  BolaDeDiscotecaTemplateVioleta: cargar(() => import("./BolaDeDiscotecaTemplateVioleta"), "BolaDeDiscotecaTemplateVioleta"),
  BonVoyageTemplate: cargar(() => import("./BonVoyageTemplate"), "BonVoyageTemplate"),
  BonVoyageTemplateArenaCalida: cargar(() => import("./BonVoyageTemplateArenaCalida"), "BonVoyageTemplateArenaCalida"),
  BonVoyageTemplateCoral: cargar(() => import("./BonVoyageTemplateCoral"), "BonVoyageTemplateCoral"),
  BonVoyageTemplateCoralTropical: cargar(() => import("./BonVoyageTemplateCoralTropical"), "BonVoyageTemplateCoralTropical"),
  BonVoyageTemplateEsmeralda: cargar(() => import("./BonVoyageTemplateEsmeralda"), "BonVoyageTemplateEsmeralda"),
  BonVoyageTemplateIvoire: cargar(() => import("./BonVoyageTemplateIvoire"), "BonVoyageTemplateIvoire"),
  BonVoyageTemplateLavanda: cargar(() => import("./BonVoyageTemplateLavanda"), "BonVoyageTemplateLavanda"),
  BonVoyageTemplateMapaVintage: cargar(() => import("./BonVoyageTemplateMapaVintage"), "BonVoyageTemplateMapaVintage"),
  BonVoyageTemplateMedianoche: cargar(() => import("./BonVoyageTemplateMedianoche"), "BonVoyageTemplateMedianoche"),
  BonVoyageTemplateNocheDeViaje: cargar(() => import("./BonVoyageTemplateNocheDeViaje"), "BonVoyageTemplateNocheDeViaje"),
  BonVoyageTemplateTurquesa: cargar(() => import("./BonVoyageTemplateTurquesa"), "BonVoyageTemplateTurquesa"),
  BotanicaEditorialTemplate: cargar(() => import("./BotanicaEditorialTemplate"), "BotanicaEditorialTemplate"),
  BotanicaEditorialTemplateBorgona: cargar(() => import("./BotanicaEditorialTemplateBorgona"), "BotanicaEditorialTemplateBorgona"),
  BotanicaEditorialTemplateIndigo: cargar(() => import("./BotanicaEditorialTemplateIndigo"), "BotanicaEditorialTemplateIndigo"),
  BotanicaEditorialTemplateLavanda: cargar(() => import("./BotanicaEditorialTemplateLavanda"), "BotanicaEditorialTemplateLavanda"),
  BotanicaEditorialTemplateTerracota: cargar(() => import("./BotanicaEditorialTemplateTerracota"), "BotanicaEditorialTemplateTerracota"),
  BurbujaPase: cargar(() => import("./BurbujaPase"), "BurbujaPase"),
  CeramicaEditorialTemplate: cargar(() => import("./CeramicaEditorialTemplate"), "CeramicaEditorialTemplate"),
  CeramicaEditorialTemplateCeladon: cargar(() => import("./CeramicaEditorialTemplateCeladon"), "CeramicaEditorialTemplateCeladon"),
  CeramicaEditorialTemplateCobalto: cargar(() => import("./CeramicaEditorialTemplateCobalto"), "CeramicaEditorialTemplateCobalto"),
  CeramicaEditorialTemplateGrisPiedra: cargar(() => import("./CeramicaEditorialTemplateGrisPiedra"), "CeramicaEditorialTemplateGrisPiedra"),
  CeramicaEditorialTemplateTerracota: cargar(() => import("./CeramicaEditorialTemplateTerracota"), "CeramicaEditorialTemplateTerracota"),
  ChicTemplate: cargar(() => import("./ChicTemplate"), "ChicTemplate"),
  ChicTemplateAmbar: cargar(() => import("./ChicTemplateAmbar"), "ChicTemplateAmbar"),
  ChicTemplateAzul: cargar(() => import("./ChicTemplateAzul"), "ChicTemplateAzul"),
  ChicTemplateAzulMedianocheChic: cargar(() => import("./ChicTemplateAzulMedianocheChic"), "ChicTemplateAzulMedianocheChic"),
  ChicTemplateGris: cargar(() => import("./ChicTemplateGris"), "ChicTemplateGris"),
  ChicTemplateNocheChic: cargar(() => import("./ChicTemplateNocheChic"), "ChicTemplateNocheChic"),
  ChicTemplatePiedraChic: cargar(() => import("./ChicTemplatePiedraChic"), "ChicTemplatePiedraChic"),
  ChicTemplateRosa: cargar(() => import("./ChicTemplateRosa"), "ChicTemplateRosa"),
  ChicTemplateTerracota: cargar(() => import("./ChicTemplateTerracota"), "ChicTemplateTerracota"),
  ChicTemplateVerdeBotella: cargar(() => import("./ChicTemplateVerdeBotella"), "ChicTemplateVerdeBotella"),
  ChicTemplateVioleta: cargar(() => import("./ChicTemplateVioleta"), "ChicTemplateVioleta"),
  CineAbstractoTemplate: cargar(() => import("./CineAbstractoTemplate"), "CineAbstractoTemplate"),
  CineAbstractoTemplateBlancoNegroPlata: cargar(() => import("./CineAbstractoTemplateBlancoNegroPlata"), "CineAbstractoTemplateBlancoNegroPlata"),
  CineAbstractoTemplateNoirEsmeralda: cargar(() => import("./CineAbstractoTemplateNoirEsmeralda"), "CineAbstractoTemplateNoirEsmeralda"),
  CineAbstractoTemplateSepiaClasico: cargar(() => import("./CineAbstractoTemplateSepiaClasico"), "CineAbstractoTemplateSepiaClasico"),
  CineAbstractoTemplateTecnicolorAzulNaranja: cargar(() => import("./CineAbstractoTemplateTecnicolorAzulNaranja"), "CineAbstractoTemplateTecnicolorAzulNaranja"),
  CineAbstractoXvTemplate: cargar(() => import("./CineAbstractoXvTemplate"), "CineAbstractoXvTemplate"),
  CineAbstractoXvTemplateNoir: cargar(() => import("./CineAbstractoXvTemplateNoir"), "CineAbstractoXvTemplateNoir"),
  CineAbstractoXvTemplateSciFi: cargar(() => import("./CineAbstractoXvTemplateSciFi"), "CineAbstractoXvTemplateSciFi"),
  CineAbstractoXvTemplateTecnicolor: cargar(() => import("./CineAbstractoXvTemplateTecnicolor"), "CineAbstractoXvTemplateTecnicolor"),
  CineAbstractoXvTemplateWestern: cargar(() => import("./CineAbstractoXvTemplateWestern"), "CineAbstractoXvTemplateWestern"),
  CineTemplate: cargar(() => import("./CineTemplate"), "CineTemplate"),
  CineTemplateAmbar: cargar(() => import("./CineTemplateAmbar"), "CineTemplateAmbar"),
  CineTemplateBlancoYNegro: cargar(() => import("./CineTemplateBlancoYNegro"), "CineTemplateBlancoYNegro"),
  CineTemplateBorgona: cargar(() => import("./CineTemplateBorgona"), "CineTemplateBorgona"),
  CineTemplateEsmeralda: cargar(() => import("./CineTemplateEsmeralda"), "CineTemplateEsmeralda"),
  CineTemplateMedianocheDeCine: cargar(() => import("./CineTemplateMedianocheDeCine"), "CineTemplateMedianocheDeCine"),
  CineTemplateNoir: cargar(() => import("./CineTemplateNoir"), "CineTemplateNoir"),
  CineTemplateOcreVintage: cargar(() => import("./CineTemplateOcreVintage"), "CineTemplateOcreVintage"),
  CineTemplateTecnicolor: cargar(() => import("./CineTemplateTecnicolor"), "CineTemplateTecnicolor"),
  CircuitoTemplate: cargar(() => import("./CircuitoTemplate"), "CircuitoTemplate"),
  CircuitoTemplateAmbar: cargar(() => import("./CircuitoTemplateAmbar"), "CircuitoTemplateAmbar"),
  CircuitoTemplateAzul: cargar(() => import("./CircuitoTemplateAzul"), "CircuitoTemplateAzul"),
  CircuitoTemplateLima: cargar(() => import("./CircuitoTemplateLima"), "CircuitoTemplateLima"),
  CircuitoTemplateRojo: cargar(() => import("./CircuitoTemplateRojo"), "CircuitoTemplateRojo"),
  CircuitoTemplateVioleta: cargar(() => import("./CircuitoTemplateVioleta"), "CircuitoTemplateVioleta"),
  CollaborativeAlbumModern: cargar(() => import("./CollaborativeAlbumModern"), "CollaborativeAlbumModern"),
  ConviteTemplate: cargar(() => import("./ConviteTemplate"), "ConviteTemplate"),
  CoronaEscarlataTemplate: cargar(() => import("./CoronaEscarlataTemplate"), "CoronaEscarlataTemplate"),
  CoronaEscarlataTemplateEsmeralda: cargar(() => import("./CoronaEscarlataTemplateEsmeralda"), "CoronaEscarlataTemplateEsmeralda"),
  CoronaEscarlataTemplateImperial: cargar(() => import("./CoronaEscarlataTemplateImperial"), "CoronaEscarlataTemplateImperial"),
  CoronaEscarlataTemplateMedianoche: cargar(() => import("./CoronaEscarlataTemplateMedianoche"), "CoronaEscarlataTemplateMedianoche"),
  CoronaEscarlataTemplateZafiro: cargar(() => import("./CoronaEscarlataTemplateZafiro"), "CoronaEscarlataTemplateZafiro"),
  CorporateTemplate: cargar(() => import("./CorporateTemplate"), "CorporateTemplate"),
  CorporateTemplateBordo: cargar(() => import("./CorporateTemplateBordo"), "CorporateTemplateBordo"),
  CorporateTemplateClaro: cargar(() => import("./CorporateTemplateClaro"), "CorporateTemplateClaro"),
  CorporateTemplateVerde: cargar(() => import("./CorporateTemplateVerde"), "CorporateTemplateVerde"),
  CorporateTemplateVioleta: cargar(() => import("./CorporateTemplateVioleta"), "CorporateTemplateVioleta"),
  CorporativoAniversarioTemplate: cargar(() => import("./CorporativoAniversarioTemplate"), "CorporativoAniversarioTemplate"),
  CorporativoAniversarioTemplateBorgona: cargar(() => import("./CorporativoAniversarioTemplateBorgona"), "CorporativoAniversarioTemplateBorgona"),
  CorporativoAniversarioTemplateEsmeralda: cargar(() => import("./CorporativoAniversarioTemplateEsmeralda"), "CorporativoAniversarioTemplateEsmeralda"),
  CorporativoAniversarioTemplateGrafito: cargar(() => import("./CorporativoAniversarioTemplateGrafito"), "CorporativoAniversarioTemplateGrafito"),
  CorporativoAniversarioTemplatePlata: cargar(() => import("./CorporativoAniversarioTemplatePlata"), "CorporativoAniversarioTemplatePlata"),
  CorporativoEncuentroTemplate: cargar(() => import("./CorporativoEncuentroTemplate"), "CorporativoEncuentroTemplate"),
  CorporativoEncuentroTemplateAzul: cargar(() => import("./CorporativoEncuentroTemplateAzul"), "CorporativoEncuentroTemplateAzul"),
  CorporativoEncuentroTemplateGris: cargar(() => import("./CorporativoEncuentroTemplateGris"), "CorporativoEncuentroTemplateGris"),
  CorporativoEncuentroTemplateVerde: cargar(() => import("./CorporativoEncuentroTemplateVerde"), "CorporativoEncuentroTemplateVerde"),
  CorporativoEncuentroTemplateVino: cargar(() => import("./CorporativoEncuentroTemplateVino"), "CorporativoEncuentroTemplateVino"),
  Cristal3DTemplate: cargar(() => import("./Cristal3DTemplate"), "Cristal3DTemplate"),
  Cristal3DTemplateAmbar: cargar(() => import("./Cristal3DTemplateAmbar"), "Cristal3DTemplateAmbar"),
  Cristal3DTemplateAmbarFundido: cargar(() => import("./Cristal3DTemplateAmbarFundido"), "Cristal3DTemplateAmbarFundido"),
  Cristal3DTemplateCristalBlanco: cargar(() => import("./Cristal3DTemplateCristalBlanco"), "Cristal3DTemplateCristalBlanco"),
  Cristal3DTemplateEsmeralda: cargar(() => import("./Cristal3DTemplateEsmeralda"), "Cristal3DTemplateEsmeralda"),
  Cristal3DTemplateMenta: cargar(() => import("./Cristal3DTemplateMenta"), "Cristal3DTemplateMenta"),
  Cristal3DTemplateRosaCristalOscuro: cargar(() => import("./Cristal3DTemplateRosaCristalOscuro"), "Cristal3DTemplateRosaCristalOscuro"),
  Cristal3DTemplateRosaCuarzo: cargar(() => import("./Cristal3DTemplateRosaCuarzo"), "Cristal3DTemplateRosaCuarzo"),
  Cristal3DTemplateVioleta: cargar(() => import("./Cristal3DTemplateVioleta"), "Cristal3DTemplateVioleta"),
  Crystal3dTemplate: cargar(() => import("./Crystal3dTemplate"), "Crystal3dTemplate"),
  Crystal3dTemplateAmbarBronce: cargar(() => import("./Crystal3dTemplateAmbarBronce"), "Crystal3dTemplateAmbarBronce"),
  Crystal3dTemplateCuarzoRosa: cargar(() => import("./Crystal3dTemplateCuarzoRosa"), "Crystal3dTemplateCuarzoRosa"),
  Crystal3dTemplateEsmeraldaPlata: cargar(() => import("./Crystal3dTemplateEsmeraldaPlata"), "Crystal3dTemplateEsmeraldaPlata"),
  Crystal3dTemplateZafiroBlanco: cargar(() => import("./Crystal3dTemplateZafiroBlanco"), "Crystal3dTemplateZafiroBlanco"),
  CumpleanosCocktailTemplate: cargar(() => import("./CumpleanosCocktailTemplate"), "CumpleanosCocktailTemplate"),
  CumpleanosCocktailTemplateEsmeralda: cargar(() => import("./CumpleanosCocktailTemplateEsmeralda"), "CumpleanosCocktailTemplateEsmeralda"),
  CumpleanosCocktailTemplatePlata: cargar(() => import("./CumpleanosCocktailTemplatePlata"), "CumpleanosCocktailTemplatePlata"),
  CumpleanosCocktailTemplateRubi: cargar(() => import("./CumpleanosCocktailTemplateRubi"), "CumpleanosCocktailTemplateRubi"),
  CumpleanosCocktailTemplateZafiro: cargar(() => import("./CumpleanosCocktailTemplateZafiro"), "CumpleanosCocktailTemplateZafiro"),
  CumpleanosJardinTemplate: cargar(() => import("./CumpleanosJardinTemplate"), "CumpleanosJardinTemplate"),
  CumpleanosJardinTemplateAzulado: cargar(() => import("./CumpleanosJardinTemplateAzulado"), "CumpleanosJardinTemplateAzulado"),
  CumpleanosJardinTemplateCoral: cargar(() => import("./CumpleanosJardinTemplateCoral"), "CumpleanosJardinTemplateCoral"),
  CumpleanosJardinTemplateDorado: cargar(() => import("./CumpleanosJardinTemplateDorado"), "CumpleanosJardinTemplateDorado"),
  CumpleanosJardinTemplateLavanda: cargar(() => import("./CumpleanosJardinTemplateLavanda"), "CumpleanosJardinTemplateLavanda"),
  CumpleanosTerrazaTemplate: cargar(() => import("./CumpleanosTerrazaTemplate"), "CumpleanosTerrazaTemplate"),
  CumpleanosTerrazaTemplateAzul: cargar(() => import("./CumpleanosTerrazaTemplateAzul"), "CumpleanosTerrazaTemplateAzul"),
  CumpleanosTerrazaTemplateEsmeralda: cargar(() => import("./CumpleanosTerrazaTemplateEsmeralda"), "CumpleanosTerrazaTemplateEsmeralda"),
  CumpleanosTerrazaTemplateMalva: cargar(() => import("./CumpleanosTerrazaTemplateMalva"), "CumpleanosTerrazaTemplateMalva"),
  CumpleanosTerrazaTemplateRojo: cargar(() => import("./CumpleanosTerrazaTemplateRojo"), "CumpleanosTerrazaTemplateRojo"),
  DespedidaSolteraTemplate: cargar(() => import("./DespedidaSolteraTemplate"), "DespedidaSolteraTemplate"),
  DespedidaSolteraTemplateCoral: cargar(() => import("./DespedidaSolteraTemplateCoral"), "DespedidaSolteraTemplateCoral"),
  DespedidaSolteraTemplateDorado: cargar(() => import("./DespedidaSolteraTemplateDorado"), "DespedidaSolteraTemplateDorado"),
  DespedidaSolteraTemplateTurquesa: cargar(() => import("./DespedidaSolteraTemplateTurquesa"), "DespedidaSolteraTemplateTurquesa"),
  DespedidaSolteraTemplateVioleta: cargar(() => import("./DespedidaSolteraTemplateVioleta"), "DespedidaSolteraTemplateVioleta"),
  DespedidaSolteroTemplate: cargar(() => import("./DespedidaSolteroTemplate"), "DespedidaSolteroTemplate"),
  DespedidaSolteroTemplateDorado: cargar(() => import("./DespedidaSolteroTemplateDorado"), "DespedidaSolteroTemplateDorado"),
  DespedidaSolteroTemplateEsmeralda: cargar(() => import("./DespedidaSolteroTemplateEsmeralda"), "DespedidaSolteroTemplateEsmeralda"),
  DespedidaSolteroTemplateGrafito: cargar(() => import("./DespedidaSolteroTemplateGrafito"), "DespedidaSolteroTemplateGrafito"),
  DespedidaSolteroTemplateVino: cargar(() => import("./DespedidaSolteroTemplateVino"), "DespedidaSolteroTemplateVino"),
  DraftTemplate: cargar(() => import("./DraftTemplate"), "DraftTemplate"),
  EditorialTemplate: cargar(() => import("./EditorialTemplate"), "EditorialTemplate"),
  EditorialTemplateAzul: cargar(() => import("./EditorialTemplateAzul"), "EditorialTemplateAzul"),
  EditorialTemplateCobalto: cargar(() => import("./EditorialTemplateCobalto"), "EditorialTemplateCobalto"),
  EditorialTemplateGrafito: cargar(() => import("./EditorialTemplateGrafito"), "EditorialTemplateGrafito"),
  EditorialTemplateGris: cargar(() => import("./EditorialTemplateGris"), "EditorialTemplateGris"),
  EditorialTemplateMalva: cargar(() => import("./EditorialTemplateMalva"), "EditorialTemplateMalva"),
  EditorialTemplateOnice: cargar(() => import("./EditorialTemplateOnice"), "EditorialTemplateOnice"),
  EditorialTemplatePiedra: cargar(() => import("./EditorialTemplatePiedra"), "EditorialTemplatePiedra"),
  EditorialTemplateTerracota: cargar(() => import("./EditorialTemplateTerracota"), "EditorialTemplateTerracota"),
  EditorialTemplateVerde: cargar(() => import("./EditorialTemplateVerde"), "EditorialTemplateVerde"),
  ElegantTemplate: cargar(() => import("./ElegantTemplate"), "ElegantTemplate"),
  ElegantTemplateBlue: cargar(() => import("./ElegantTemplateBlue"), "ElegantTemplateBlue"),
  ElegantTemplateDarkYellow: cargar(() => import("./ElegantTemplateDarkYellow"), "ElegantTemplateDarkYellow"),
  ElegantTemplateGray: cargar(() => import("./ElegantTemplateGray"), "ElegantTemplateGray"),
  ElegantTemplateGreen: cargar(() => import("./ElegantTemplateGreen"), "ElegantTemplateGreen"),
  ElegantTemplateOrange: cargar(() => import("./ElegantTemplateOrange"), "ElegantTemplateOrange"),
  ElegantTemplatePink: cargar(() => import("./ElegantTemplatePink"), "ElegantTemplatePink"),
  ElegantTemplateRed: cargar(() => import("./ElegantTemplateRed"), "ElegantTemplateRed"),
  ElegantTemplateViolet: cargar(() => import("./ElegantTemplateViolet"), "ElegantTemplateViolet"),
  EncajeContemporaneoTemplate: cargar(() => import("./EncajeContemporaneoTemplate"), "EncajeContemporaneoTemplate"),
  EncajeContemporaneoTemplateAzulMedianoche: cargar(() => import("./EncajeContemporaneoTemplateAzulMedianoche"), "EncajeContemporaneoTemplateAzulMedianoche"),
  EncajeContemporaneoTemplateBorgona: cargar(() => import("./EncajeContemporaneoTemplateBorgona"), "EncajeContemporaneoTemplateBorgona"),
  EncajeContemporaneoTemplateGrisPiedra: cargar(() => import("./EncajeContemporaneoTemplateGrisPiedra"), "EncajeContemporaneoTemplateGrisPiedra"),
  EncajeContemporaneoTemplateVerdeBosque: cargar(() => import("./EncajeContemporaneoTemplateVerdeBosque"), "EncajeContemporaneoTemplateVerdeBosque"),
  FashionLookbookTemplate: cargar(() => import("./FashionLookbookTemplate"), "FashionLookbookTemplate"),
  FashionLookbookTemplateCobalto: cargar(() => import("./FashionLookbookTemplateCobalto"), "FashionLookbookTemplateCobalto"),
  FashionLookbookTemplateMagenta: cargar(() => import("./FashionLookbookTemplateMagenta"), "FashionLookbookTemplateMagenta"),
  FashionLookbookTemplateMilitar: cargar(() => import("./FashionLookbookTemplateMilitar"), "FashionLookbookTemplateMilitar"),
  FashionLookbookTemplateMostaza: cargar(() => import("./FashionLookbookTemplateMostaza"), "FashionLookbookTemplateMostaza"),
  FashionTagTemplate: cargar(() => import("./FashionTagTemplate"), "FashionTagTemplate"),
  FashionTagTemplateBottleGreen: cargar(() => import("./FashionTagTemplateBottleGreen"), "FashionTagTemplateBottleGreen"),
  FashionTagTemplateBurgundy: cargar(() => import("./FashionTagTemplateBurgundy"), "FashionTagTemplateBurgundy"),
  FashionTagTemplateGoldenMustard: cargar(() => import("./FashionTagTemplateGoldenMustard"), "FashionTagTemplateGoldenMustard"),
  FashionTagTemplateMidnightNavy: cargar(() => import("./FashionTagTemplateMidnightNavy"), "FashionTagTemplateMidnightNavy"),
  GardenPartyTemplate: cargar(() => import("./GardenPartyTemplate"), "GardenPartyTemplate"),
  GardenPartyTemplateAmarillo: cargar(() => import("./GardenPartyTemplateAmarillo"), "GardenPartyTemplateAmarillo"),
  GardenPartyTemplateLavanda: cargar(() => import("./GardenPartyTemplateLavanda"), "GardenPartyTemplateLavanda"),
  GardenPartyTemplateRosa: cargar(() => import("./GardenPartyTemplateRosa"), "GardenPartyTemplateRosa"),
  GardenPartyTemplateVibrante: cargar(() => import("./GardenPartyTemplateVibrante"), "GardenPartyTemplateVibrante"),
  GoldenDuskTemplate: cargar(() => import("./GoldenDuskTemplate"), "GoldenDuskTemplate"),
  GoldenDuskTemplateAzulMedianoche: cargar(() => import("./GoldenDuskTemplateAzulMedianoche"), "GoldenDuskTemplateAzulMedianoche"),
  GoldenDuskTemplateBorgona: cargar(() => import("./GoldenDuskTemplateBorgona"), "GoldenDuskTemplateBorgona"),
  GoldenDuskTemplateBrumaAzul: cargar(() => import("./GoldenDuskTemplateBrumaAzul"), "GoldenDuskTemplateBrumaAzul"),
  GoldenDuskTemplateChampagneDorado: cargar(() => import("./GoldenDuskTemplateChampagneDorado"), "GoldenDuskTemplateChampagneDorado"),
  GoldenDuskTemplateNocheCiruela: cargar(() => import("./GoldenDuskTemplateNocheCiruela"), "GoldenDuskTemplateNocheCiruela"),
  GoldenDuskTemplateNocheDorada: cargar(() => import("./GoldenDuskTemplateNocheDorada"), "GoldenDuskTemplateNocheDorada"),
  GoldenDuskTemplateOcaso: cargar(() => import("./GoldenDuskTemplateOcaso"), "GoldenDuskTemplateOcaso"),
  GoldenDuskTemplatePiedraCalida: cargar(() => import("./GoldenDuskTemplatePiedraCalida"), "GoldenDuskTemplatePiedraCalida"),
  GoldenDuskTemplateRosaAntiguo: cargar(() => import("./GoldenDuskTemplateRosaAntiguo"), "GoldenDuskTemplateRosaAntiguo"),
  GoldenDuskTemplateSalvia: cargar(() => import("./GoldenDuskTemplateSalvia"), "GoldenDuskTemplateSalvia"),
  GraduacionTemplate: cargar(() => import("./GraduacionTemplate"), "GraduacionTemplate"),
  GraduacionTemplateAzul: cargar(() => import("./GraduacionTemplateAzul"), "GraduacionTemplateAzul"),
  GraduacionTemplateBorgona: cargar(() => import("./GraduacionTemplateBorgona"), "GraduacionTemplateBorgona"),
  GraduacionTemplatePlata: cargar(() => import("./GraduacionTemplatePlata"), "GraduacionTemplatePlata"),
  GraduacionTemplateVerde: cargar(() => import("./GraduacionTemplateVerde"), "GraduacionTemplateVerde"),
  GuestPassVipTemplate: cargar(() => import("./GuestPassVipTemplate"), "GuestPassVipTemplate"),
  GuestPassVipTemplateBorgona: cargar(() => import("./GuestPassVipTemplateBorgona"), "GuestPassVipTemplateBorgona"),
  GuestPassVipTemplateEsmeralda: cargar(() => import("./GuestPassVipTemplateEsmeralda"), "GuestPassVipTemplateEsmeralda"),
  GuestPassVipTemplatePlata: cargar(() => import("./GuestPassVipTemplatePlata"), "GuestPassVipTemplatePlata"),
  GuestPassVipTemplateZafiro: cargar(() => import("./GuestPassVipTemplateZafiro"), "GuestPassVipTemplateZafiro"),
  HologramaTemplate: cargar(() => import("./HologramaTemplate"), "HologramaTemplate"),
  HologramaTemplateAurora: cargar(() => import("./HologramaTemplateAurora"), "HologramaTemplateAurora"),
  HologramaTemplateAzul: cargar(() => import("./HologramaTemplateAzul"), "HologramaTemplateAzul"),
  HologramaTemplateBlancoPrisma: cargar(() => import("./HologramaTemplateBlancoPrisma"), "HologramaTemplateBlancoPrisma"),
  HologramaTemplateCoral: cargar(() => import("./HologramaTemplateCoral"), "HologramaTemplateCoral"),
  HologramaTemplateDorado: cargar(() => import("./HologramaTemplateDorado"), "HologramaTemplateDorado"),
  HologramaTemplateEsmeralda: cargar(() => import("./HologramaTemplateEsmeralda"), "HologramaTemplateEsmeralda"),
  HologramaTemplateGrafitoCuantico: cargar(() => import("./HologramaTemplateGrafitoCuantico"), "HologramaTemplateGrafitoCuantico"),
  HologramaTemplateNebulosaRoja: cargar(() => import("./HologramaTemplateNebulosaRoja"), "HologramaTemplateNebulosaRoja"),
  HologramaTemplateRosa: cargar(() => import("./HologramaTemplateRosa"), "HologramaTemplateRosa"),
  InauguracionTemplate: cargar(() => import("./InauguracionTemplate"), "InauguracionTemplate"),
  InauguracionTemplateAzul: cargar(() => import("./InauguracionTemplateAzul"), "InauguracionTemplateAzul"),
  InauguracionTemplateCobre: cargar(() => import("./InauguracionTemplateCobre"), "InauguracionTemplateCobre"),
  InauguracionTemplateEsmeralda: cargar(() => import("./InauguracionTemplateEsmeralda"), "InauguracionTemplateEsmeralda"),
  InauguracionTemplateGrafito: cargar(() => import("./InauguracionTemplateGrafito"), "InauguracionTemplateGrafito"),
  InfantilEspacioTemplate: cargar(() => import("./InfantilEspacioTemplate"), "InfantilEspacioTemplate"),
  InfantilEspacioTemplateDorado: cargar(() => import("./InfantilEspacioTemplateDorado"), "InfantilEspacioTemplateDorado"),
  InfantilEspacioTemplateRosa: cargar(() => import("./InfantilEspacioTemplateRosa"), "InfantilEspacioTemplateRosa"),
  InfantilEspacioTemplateVerde: cargar(() => import("./InfantilEspacioTemplateVerde"), "InfantilEspacioTemplateVerde"),
  InfantilEspacioTemplateVioleta: cargar(() => import("./InfantilEspacioTemplateVioleta"), "InfantilEspacioTemplateVioleta"),
  InfantilJurasicoTemplate: cargar(() => import("./InfantilJurasicoTemplate"), "InfantilJurasicoTemplate"),
  InfantilJurasicoTemplateAmarillo: cargar(() => import("./InfantilJurasicoTemplateAmarillo"), "InfantilJurasicoTemplateAmarillo"),
  InfantilJurasicoTemplateMarron: cargar(() => import("./InfantilJurasicoTemplateMarron"), "InfantilJurasicoTemplateMarron"),
  InfantilJurasicoTemplateNaranja: cargar(() => import("./InfantilJurasicoTemplateNaranja"), "InfantilJurasicoTemplateNaranja"),
  InfantilJurasicoTemplateRojo: cargar(() => import("./InfantilJurasicoTemplateRojo"), "InfantilJurasicoTemplateRojo"),
  InfantilSafariTemplate: cargar(() => import("./InfantilSafariTemplate"), "InfantilSafariTemplate"),
  InfantilSafariTemplateAmarillo: cargar(() => import("./InfantilSafariTemplateAmarillo"), "InfantilSafariTemplateAmarillo"),
  InfantilSafariTemplateCoral: cargar(() => import("./InfantilSafariTemplateCoral"), "InfantilSafariTemplateCoral"),
  InfantilSafariTemplateTurquesa: cargar(() => import("./InfantilSafariTemplateTurquesa"), "InfantilSafariTemplateTurquesa"),
  InfantilSafariTemplateVerde: cargar(() => import("./InfantilSafariTemplateVerde"), "InfantilSafariTemplateVerde"),
  InfantilTemplate: cargar(() => import("./InfantilTemplate"), "InfantilTemplate"),
  InfantilTemplateAmarillo: cargar(() => import("./InfantilTemplateAmarillo"), "InfantilTemplateAmarillo"),
  InfantilTemplateCeleste: cargar(() => import("./InfantilTemplateCeleste"), "InfantilTemplateCeleste"),
  InfantilTemplateLavanda: cargar(() => import("./InfantilTemplateLavanda"), "InfantilTemplateLavanda"),
  InfantilTemplateMenta: cargar(() => import("./InfantilTemplateMenta"), "InfantilTemplateMenta"),
  JardinSedaTemplate: cargar(() => import("./JardinSedaTemplate"), "JardinSedaTemplate"),
  JardinSedaTemplateCielo: cargar(() => import("./JardinSedaTemplateCielo"), "JardinSedaTemplateCielo"),
  JardinSedaTemplateDurazno: cargar(() => import("./JardinSedaTemplateDurazno"), "JardinSedaTemplateDurazno"),
  JardinSedaTemplateJardinNocturno: cargar(() => import("./JardinSedaTemplateJardinNocturno"), "JardinSedaTemplateJardinNocturno"),
  JardinSedaTemplateLila: cargar(() => import("./JardinSedaTemplateLila"), "JardinSedaTemplateLila"),
  JardinSedaTemplatePiedraJardin: cargar(() => import("./JardinSedaTemplatePiedraJardin"), "JardinSedaTemplatePiedraJardin"),
  JardinSedaTemplateRosaAntiguo: cargar(() => import("./JardinSedaTemplateRosaAntiguo"), "JardinSedaTemplateRosaAntiguo"),
  JardinSedaTemplateSalvia: cargar(() => import("./JardinSedaTemplateSalvia"), "JardinSedaTemplateSalvia"),
  JardinSedaTemplateTerracotaJardin: cargar(() => import("./JardinSedaTemplateTerracotaJardin"), "JardinSedaTemplateTerracotaJardin"),
  JewelryBoxTemplate: cargar(() => import("./JewelryBoxTemplate"), "JewelryBoxTemplate"),
  JewelryBoxTemplateEsmeralda: cargar(() => import("./JewelryBoxTemplateEsmeralda"), "JewelryBoxTemplateEsmeralda"),
  JewelryBoxTemplatePerla: cargar(() => import("./JewelryBoxTemplatePerla"), "JewelryBoxTemplatePerla"),
  JewelryBoxTemplateRubi: cargar(() => import("./JewelryBoxTemplateRubi"), "JewelryBoxTemplateRubi"),
  JewelryBoxTemplateZafiro: cargar(() => import("./JewelryBoxTemplateZafiro"), "JewelryBoxTemplateZafiro"),
  LiquidGlassTemplate: cargar(() => import("./LiquidGlassTemplate"), "LiquidGlassTemplate"),
  LiquidGlassTemplateAmatista: cargar(() => import("./LiquidGlassTemplateAmatista"), "LiquidGlassTemplateAmatista"),
  LiquidGlassTemplateAmbar: cargar(() => import("./LiquidGlassTemplateAmbar"), "LiquidGlassTemplateAmbar"),
  LiquidGlassTemplateCuarzo: cargar(() => import("./LiquidGlassTemplateCuarzo"), "LiquidGlassTemplateCuarzo"),
  LiquidGlassTemplateEsmeralda: cargar(() => import("./LiquidGlassTemplateEsmeralda"), "LiquidGlassTemplateEsmeralda"),
  LiveAlbumStrip: cargar(() => import("./LiveAlbumStrip"), "LiveAlbumStrip"),
  LoftIndustrialTemplate: cargar(() => import("./LoftIndustrialTemplate"), "LoftIndustrialTemplate"),
  LoftIndustrialTemplateAcero: cargar(() => import("./LoftIndustrialTemplateAcero"), "LoftIndustrialTemplateAcero"),
  LoftIndustrialTemplateClaro: cargar(() => import("./LoftIndustrialTemplateClaro"), "LoftIndustrialTemplateClaro"),
  LoftIndustrialTemplateCobre: cargar(() => import("./LoftIndustrialTemplateCobre"), "LoftIndustrialTemplateCobre"),
  LoftIndustrialTemplateVerde: cargar(() => import("./LoftIndustrialTemplateVerde"), "LoftIndustrialTemplateVerde"),
  LuzLunaTemplate: cargar(() => import("./LuzLunaTemplate"), "LuzLunaTemplate"),
  LuzLunaTemplateMedianocheAzul: cargar(() => import("./LuzLunaTemplateMedianocheAzul"), "LuzLunaTemplateMedianocheAzul"),
  LuzLunaTemplateNocheEstrellada: cargar(() => import("./LuzLunaTemplateNocheEstrellada"), "LuzLunaTemplateNocheEstrellada"),
  LuzLunaTemplatePerlaSuave: cargar(() => import("./LuzLunaTemplatePerlaSuave"), "LuzLunaTemplatePerlaSuave"),
  LuzLunaTemplatePerlada: cargar(() => import("./LuzLunaTemplatePerlada"), "LuzLunaTemplatePerlada"),
  MarmolYOroTemplate: cargar(() => import("./MarmolYOroTemplate"), "MarmolYOroTemplate"),
  MarmolYOroTemplateBronce: cargar(() => import("./MarmolYOroTemplateBronce"), "MarmolYOroTemplateBronce"),
  MarmolYOroTemplateEsmeralda: cargar(() => import("./MarmolYOroTemplateEsmeralda"), "MarmolYOroTemplateEsmeralda"),
  MarmolYOroTemplateOnix: cargar(() => import("./MarmolYOroTemplateOnix"), "MarmolYOroTemplateOnix"),
  MarmolYOroTemplateRosa: cargar(() => import("./MarmolYOroTemplateRosa"), "MarmolYOroTemplateRosa"),
  ModernoTemplate: cargar(() => import("./ModernoTemplate"), "ModernoTemplate"),
  ModernoTemplateAzul: cargar(() => import("./ModernoTemplateAzul"), "ModernoTemplateAzul"),
  ModernoTemplateBordo: cargar(() => import("./ModernoTemplateBordo"), "ModernoTemplateBordo"),
  ModernoTemplateGris: cargar(() => import("./ModernoTemplateGris"), "ModernoTemplateGris"),
  ModernoTemplateLab: cargar(() => import("./ModernoTemplateLab"), "ModernoTemplateLab"),
  ModernoTemplateNegro: cargar(() => import("./ModernoTemplateNegro"), "ModernoTemplateNegro"),
  ModernoTemplatePurpura: cargar(() => import("./ModernoTemplatePurpura"), "ModernoTemplatePurpura"),
  ModernoTemplateRojo: cargar(() => import("./ModernoTemplateRojo"), "ModernoTemplateRojo"),
  ModernoTemplateVerde: cargar(() => import("./ModernoTemplateVerde"), "ModernoTemplateVerde"),
  NeonTemplate: cargar(() => import("./NeonTemplate"), "NeonTemplate"),
  NeonTemplateAscuas: cargar(() => import("./NeonTemplateAscuas"), "NeonTemplateAscuas"),
  NeonTemplateAzul: cargar(() => import("./NeonTemplateAzul"), "NeonTemplateAzul"),
  NeonTemplateBlackout: cargar(() => import("./NeonTemplateBlackout"), "NeonTemplateBlackout"),
  NeonTemplateDorado: cargar(() => import("./NeonTemplateDorado"), "NeonTemplateDorado"),
  NeonTemplateEclipse: cargar(() => import("./NeonTemplateEclipse"), "NeonTemplateEclipse"),
  NeonTemplateManzana: cargar(() => import("./NeonTemplateManzana"), "NeonTemplateManzana"),
  NeonTemplateRojo: cargar(() => import("./NeonTemplateRojo"), "NeonTemplateRojo"),
  NeonTemplateTropical: cargar(() => import("./NeonTemplateTropical"), "NeonTemplateTropical"),
  NeonTemplateVerde: cargar(() => import("./NeonTemplateVerde"), "NeonTemplateVerde"),
  NeonTemplateVioleta: cargar(() => import("./NeonTemplateVioleta"), "NeonTemplateVioleta"),
  NordicoTemplate: cargar(() => import("./NordicoTemplate"), "NordicoTemplate"),
  NordicoTemplateArticoAzul: cargar(() => import("./NordicoTemplateArticoAzul"), "NordicoTemplateArticoAzul"),
  NordicoTemplateBosque: cargar(() => import("./NordicoTemplateBosque"), "NordicoTemplateBosque"),
  NordicoTemplateCarbonNordico: cargar(() => import("./NordicoTemplateCarbonNordico"), "NordicoTemplateCarbonNordico"),
  NordicoTemplateMarino: cargar(() => import("./NordicoTemplateMarino"), "NordicoTemplateMarino"),
  NordicoTemplateMusgo: cargar(() => import("./NordicoTemplateMusgo"), "NordicoTemplateMusgo"),
  NordicoTemplateOcre: cargar(() => import("./NordicoTemplateOcre"), "NordicoTemplateOcre"),
  NordicoTemplatePizarra: cargar(() => import("./NordicoTemplatePizarra"), "NordicoTemplatePizarra"),
  NordicoTemplateTerracota: cargar(() => import("./NordicoTemplateTerracota"), "NordicoTemplateTerracota"),
  OnixTemplate: cargar(() => import("./OnixTemplate"), "OnixTemplate"),
  OnixTemplateAmatista: cargar(() => import("./OnixTemplateAmatista"), "OnixTemplateAmatista"),
  OnixTemplateBosque: cargar(() => import("./OnixTemplateBosque"), "OnixTemplateBosque"),
  OnixTemplateCarbon: cargar(() => import("./OnixTemplateCarbon"), "OnixTemplateCarbon"),
  OnixTemplateEsmeralda: cargar(() => import("./OnixTemplateEsmeralda"), "OnixTemplateEsmeralda"),
  OnixTemplateMarfil: cargar(() => import("./OnixTemplateMarfil"), "OnixTemplateMarfil"),
  OnixTemplateMedianoche: cargar(() => import("./OnixTemplateMedianoche"), "OnixTemplateMedianoche"),
  OnixTemplateOro: cargar(() => import("./OnixTemplateOro"), "OnixTemplateOro"),
  OnixTemplatePlata: cargar(() => import("./OnixTemplatePlata"), "OnixTemplatePlata"),
  OnixTemplateZafiro: cargar(() => import("./OnixTemplateZafiro"), "OnixTemplateZafiro"),
  PapeleriaDeHotelDeLujoTemplate: cargar(() => import("./PapeleriaDeHotelDeLujoTemplate"), "PapeleriaDeHotelDeLujoTemplate"),
  PapeleriaDeHotelDeLujoTemplateAzulMarinoPlata: cargar(() => import("./PapeleriaDeHotelDeLujoTemplateAzulMarinoPlata"), "PapeleriaDeHotelDeLujoTemplateAzulMarinoPlata"),
  PapeleriaDeHotelDeLujoTemplateBorgonaOroRosa: cargar(() => import("./PapeleriaDeHotelDeLujoTemplateBorgonaOroRosa"), "PapeleriaDeHotelDeLujoTemplateBorgonaOroRosa"),
  PapeleriaDeHotelDeLujoTemplateGrisCarbonOroBlanco: cargar(() => import("./PapeleriaDeHotelDeLujoTemplateGrisCarbonOroBlanco"), "PapeleriaDeHotelDeLujoTemplateGrisCarbonOroBlanco"),
  PapeleriaDeHotelDeLujoTemplateNegroYBronce: cargar(() => import("./PapeleriaDeHotelDeLujoTemplateNegroYBronce"), "PapeleriaDeHotelDeLujoTemplateNegroYBronce"),
  PaseVipTemplate: cargar(() => import("./PaseVipTemplate"), "PaseVipTemplate"),
  PaseVipTemplateCobre: cargar(() => import("./PaseVipTemplateCobre"), "PaseVipTemplateCobre"),
  PaseVipTemplatePlatino: cargar(() => import("./PaseVipTemplatePlatino"), "PaseVipTemplatePlatino"),
  PaseVipTemplateRubi: cargar(() => import("./PaseVipTemplateRubi"), "PaseVipTemplateRubi"),
  PaseVipTemplateVioleta: cargar(() => import("./PaseVipTemplateVioleta"), "PaseVipTemplateVioleta"),
  PetalosTemplate: cargar(() => import("./PetalosTemplate"), "PetalosTemplate"),
  PetalosTemplateCoral: cargar(() => import("./PetalosTemplateCoral"), "PetalosTemplateCoral"),
  PetalosTemplatePastel: cargar(() => import("./PetalosTemplatePastel"), "PetalosTemplatePastel"),
  PetalosTemplateRosaPastel: cargar(() => import("./PetalosTemplateRosaPastel"), "PetalosTemplateRosaPastel"),
  PetalosTemplateVinoVibrante: cargar(() => import("./PetalosTemplateVinoVibrante"), "PetalosTemplateVinoVibrante"),
  PrincesaTemplate: cargar(() => import("./PrincesaTemplate"), "PrincesaTemplate"),
  PrincesaTemplateAzulMedianoche: cargar(() => import("./PrincesaTemplateAzulMedianoche"), "PrincesaTemplateAzulMedianoche"),
  PrincesaTemplateBorgona: cargar(() => import("./PrincesaTemplateBorgona"), "PrincesaTemplateBorgona"),
  PrincesaTemplateBosqueEncantado: cargar(() => import("./PrincesaTemplateBosqueEncantado"), "PrincesaTemplateBosqueEncantado"),
  PrincesaTemplateRosaAntiguo: cargar(() => import("./PrincesaTemplateRosaAntiguo"), "PrincesaTemplateRosaAntiguo"),
  RivieraTemplate: cargar(() => import("./RivieraTemplate"), "RivieraTemplate"),
  RivieraTemplateAzulejo: cargar(() => import("./RivieraTemplateAzulejo"), "RivieraTemplateAzulejo"),
  RivieraTemplateCal: cargar(() => import("./RivieraTemplateCal"), "RivieraTemplateCal"),
  RivieraTemplateCoral: cargar(() => import("./RivieraTemplateCoral"), "RivieraTemplateCoral"),
  RivieraTemplateLavandaCostera: cargar(() => import("./RivieraTemplateLavandaCostera"), "RivieraTemplateLavandaCostera"),
  RivieraTemplateMedianocheRiviera: cargar(() => import("./RivieraTemplateMedianocheRiviera"), "RivieraTemplateMedianocheRiviera"),
  RivieraTemplateOcasoAzulejo: cargar(() => import("./RivieraTemplateOcasoAzulejo"), "RivieraTemplateOcasoAzulejo"),
  RivieraTemplateOcre: cargar(() => import("./RivieraTemplateOcre"), "RivieraTemplateOcre"),
  RivieraTemplateOliva: cargar(() => import("./RivieraTemplateOliva"), "RivieraTemplateOliva"),
  RivieraTemplatePiedraGris: cargar(() => import("./RivieraTemplatePiedraGris"), "RivieraTemplatePiedraGris"),
  SedaTemplate: cargar(() => import("./SedaTemplate"), "SedaTemplate"),
  SedaTemplateCiruela: cargar(() => import("./SedaTemplateCiruela"), "SedaTemplateCiruela"),
  SedaTemplateEsmeralda: cargar(() => import("./SedaTemplateEsmeralda"), "SedaTemplateEsmeralda"),
  SedaTemplateMarfil: cargar(() => import("./SedaTemplateMarfil"), "SedaTemplateMarfil"),
  SedaTemplateNocturna: cargar(() => import("./SedaTemplateNocturna"), "SedaTemplateNocturna"),
  SedaTemplateOnixSeda: cargar(() => import("./SedaTemplateOnixSeda"), "SedaTemplateOnixSeda"),
  SedaTemplatePerla: cargar(() => import("./SedaTemplatePerla"), "SedaTemplatePerla"),
  SedaTemplatePiedra: cargar(() => import("./SedaTemplatePiedra"), "SedaTemplatePiedra"),
  VintageEditorialTemplate: cargar(() => import("./VintageEditorialTemplate"), "VintageEditorialTemplate"),
  VintageEditorialTemplateAzulPetroleo: cargar(() => import("./VintageEditorialTemplateAzulPetroleo"), "VintageEditorialTemplateAzulPetroleo"),
  VintageEditorialTemplateBorgonaVino: cargar(() => import("./VintageEditorialTemplateBorgonaVino"), "VintageEditorialTemplateBorgonaVino"),
  VintageEditorialTemplateOlivaVintage: cargar(() => import("./VintageEditorialTemplateOlivaVintage"), "VintageEditorialTemplateOlivaVintage"),
  VintageEditorialTemplatePlataAntigua: cargar(() => import("./VintageEditorialTemplatePlataAntigua"), "VintageEditorialTemplatePlataAntigua"),
};

/** Si existe una plantilla con ese nombre exportado. */
export function esNombreDePlantilla(nombre: string): boolean {
  return Object.prototype.hasOwnProperty.call(PLANTILLAS, nombre);
}

/**
 * Dibuja la plantilla `nombre` con las props de siempre. Con un nombre
 * desconocido no dibuja nada: las páginas eligen el nombre con su propio
 * switch, así que acá no debería pasar nunca.
 */
export function PlantillaDinamica({ nombre, ...props }: PropsDePlantilla & { nombre: string }) {
  const Plantilla = PLANTILLAS[nombre];
  if (!Plantilla) return null;
  return <Plantilla {...props} />;
}
