-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Invitation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "tipo" TEXT NOT NULL,
    "estado" TEXT NOT NULL DEFAULT 'BORRADOR',
    "slug" TEXT NOT NULL,
    "nombreEvento" TEXT NOT NULL,
    "fechaEvento" DATETIME NOT NULL,
    "nombreNovio" TEXT,
    "nombreNovia" TEXT,
    "nombreQuinceanera" TEXT,
    "lugarNombre" TEXT,
    "direccion" TEXT,
    "hora" TEXT,
    "mapUrl" TEXT,
    "templateId" TEXT NOT NULL,
    "temaColores" TEXT NOT NULL,
    "musicaUrl" TEXT,
    "portadaHabilitada" BOOLEAN NOT NULL DEFAULT true,
    "portadaTitulo" TEXT,
    "portadaTextoBoton" TEXT,
    "portadaImagenFondo" TEXT,
    "musicaHabilitada" BOOLEAN NOT NULL DEFAULT true,
    "musicaAutoplay" BOOLEAN NOT NULL DEFAULT true,
    "musicaLoop" BOOLEAN NOT NULL DEFAULT true,
    "contadorHabilitado" BOOLEAN NOT NULL DEFAULT true,
    "seccionCuandoHabilitada" BOOLEAN NOT NULL DEFAULT true,
    "seccionCuandoIcono" TEXT,
    "seccionCuandoTitulo" TEXT,
    "seccionDondeHabilitada" BOOLEAN NOT NULL DEFAULT true,
    "seccionDondeIcono" TEXT,
    "seccionDondeTitulo" TEXT,
    "lugarBotonTexto" TEXT,
    "dresscodeHabilitado" BOOLEAN NOT NULL DEFAULT false,
    "dresscodeIcono" TEXT,
    "dresscodeTitulo" TEXT,
    "dresscodeTipo" TEXT,
    "dresscodeObservaciones" TEXT,
    "galeriaPrincipalHabilitada" BOOLEAN NOT NULL DEFAULT true,
    "galeriaPrincipalFotos" TEXT,
    "galeriaPrincipalEstilo" TEXT,
    "galeriaPrincipalAutoplay" BOOLEAN NOT NULL DEFAULT false,
    "frasePersonalizadaHabilitada" BOOLEAN NOT NULL DEFAULT false,
    "frasePersonalizadaTexto" TEXT,
    "frasePersonalizadaEstilo" TEXT,
    "albumCompartidoHabilitado" BOOLEAN NOT NULL DEFAULT true,
    "albumCompartidoIcono" TEXT,
    "albumCompartidoTitulo" TEXT,
    "albumCompartidoDescripcion" TEXT,
    "albumCompartidoBotonTexto" TEXT,
    "regaloHabilitado" BOOLEAN NOT NULL DEFAULT false,
    "regaloIcono" TEXT,
    "regaloTitulo" TEXT,
    "regaloMensaje" TEXT,
    "regaloMostrarDatos" BOOLEAN NOT NULL DEFAULT false,
    "regaloAlias" TEXT,
    "regaloCvu" TEXT,
    "regaloCbu" TEXT,
    "galeriaSecundariaHabilitada" BOOLEAN NOT NULL DEFAULT false,
    "galeriaSecundariaFotos" TEXT,
    "mensajeFinalHabilitado" BOOLEAN NOT NULL DEFAULT false,
    "mensajeFinalTexto" TEXT,
    "triviaHabilitada" BOOLEAN NOT NULL DEFAULT false,
    "triviaIcono" TEXT,
    "triviaTitulo" TEXT,
    "triviaSubtitulo" TEXT,
    "triviaPreguntas" TEXT,
    "triviaBotonTexto" TEXT,
    "confirmacionHabilitada" BOOLEAN NOT NULL DEFAULT true,
    "confirmacionIcono" TEXT,
    "confirmacionTitulo" TEXT,
    "confirmacionFechaLimite" DATETIME,
    "confirmacionWhatsapp" TEXT,
    "confirmacionEmail" TEXT,
    "despedidaHabilitada" BOOLEAN NOT NULL DEFAULT false,
    "despedidaIcono" TEXT,
    "despedidaTexto" TEXT,
    "despedidaFoto" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Invitation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_Invitation" ("createdAt", "direccion", "estado", "fechaEvento", "hora", "id", "lugarNombre", "mapUrl", "musicaUrl", "nombreEvento", "nombreNovia", "nombreNovio", "nombreQuinceanera", "slug", "temaColores", "templateId", "tipo", "updatedAt", "userId") SELECT "createdAt", "direccion", "estado", "fechaEvento", "hora", "id", "lugarNombre", "mapUrl", "musicaUrl", "nombreEvento", "nombreNovia", "nombreNovio", "nombreQuinceanera", "slug", "temaColores", "templateId", "tipo", "updatedAt", "userId" FROM "Invitation";
DROP TABLE "Invitation";
ALTER TABLE "new_Invitation" RENAME TO "Invitation";
CREATE UNIQUE INDEX "Invitation_slug_key" ON "Invitation"("slug");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
